Opentrons/opentrons-emulation

README.md

README update about using Github Action
* See above
Does this blurb and the example linked in it provide enough info to utilize the Action?
None, it would be really impressive if I broke something by updating a README

chore: Add blurb about utilizing Github Action

---

action.yaml

chore: Need to specify headless

---

scripts/setup_can.sh
scripts/teardown_can.sh

feat: Specify vcan network names from CLI

---

scripts/setup_docker.sh
scripts/setup_vm.sh
virtual-box-setup.md

Rough Virtual Box setup
Add README and setup scripts
Try out setting up a machine
None

feat: Add Virtual Box setup instructions

---

emulation_system/resources/docker/Dockerfile
emulation_system/resources/docker/entrypoint.sh

Add firmware level Thermocycler emulator
- Add to Dockerfile to create prod and dev thermocycler images
- Add build and run commands to entrypoint.sh
None
None, just adding an image that nothing depends on

feat: Add firmware level Thermocycler emulator

---

emulation_system/emulation_system/commands/abstract_command_creator.py
emulation_system/emulation_system/commands/emulation_command_creator.py
emulation_system/emulation_system/commands/virtual_machine_command_creator.py
emulation_system/emulation_system/compose_file_creator/input/configuration_file.py
emulation_system/emulation_system/opentrons_emulation_configuration.py
emulation_system/emulation_system/parsers/abstract_parser.py
emulation_system/emulation_system/parsers/emulation_parser.py
emulation_system/emulation_system/parsers/repo_parser.py
emulation_system/emulation_system/parsers/top_level_parser.py
emulation_system/emulation_system/parsers/virtual_machine_parser.py
emulation_system/tests/conftest.py
emulation_system/tests/test_configuration.json

Small refactor to prep for adding tests
- Rename `ConfigurationSettings` to `OpentronsEmulationConfiguration` and cascade rename
- Add `emulation_configuration_file_locations` property to `OpentronsEmulationConfiguration` and account for setting addition in `test_configuration.json`
None
Low

refactor: Small refactor

---

emulation_system/resources/docker/Dockerfile
emulation_system/resources/docker/docker-compose-dev.yaml
emulation_system/resources/docker/docker-compose.yaml
emulation_system/resources/docker/entrypoint.sh

Update Docker Resources
entrypoint.sh
Append either `hardware` or `firmware` to build and run commands
Add python building steps to firmware build commands
Add error handling if command is not found
Dockerfile
Rename some of the OPENTRONS_HARDWARE env vars
Pull firmware-builder build commands and add it to entrypoint.sh
Compose Files
Remove links, add networks
Update names
Remove ports from proxy as it is using a network
None
Low

chore: Update Docker Resources

---

emulation_system/emulation_system/compose_file_creator/conversion/service_creator.py
emulation_system/tests/compose_file_creator/test_conversion_logic.py

Add emulator proxy environment variables to robot server
- [service_creator.py](https://github.com/Opentrons/opentrons-emulation/pull/56/files#diff-2c156182f7bf5f2c2c6e11912fa49a4d369e664279af1a5f56960da26e28048b)
- Add _generate_robot_server_env_vars function
- Add tests to make sure env var is created at the appropriate time and correctly
I have to cast to the type `ListOrDict` [here](https://github.com/Opentrons/opentrons-emulation/pull/56/files#diff-2c156182f7bf5f2c2c6e11912fa49a4d369e664279af1a5f56960da26e28048bR116). This is because the generated docker-compose pydantic model expects a `ListOrDict` type [here](https://github.com/Opentrons/opentrons-emulation/blob/robot-server-em-proxy-env-vars-RET-429/emulation_system/emulation_system/compose_file_creator/output/compose_file_model.py …

feat: Add emulator proxy env variables to robot server

---

emulation_system/emulation_system/compose_file_creator/conversion/service_creation/__init__.py
emulation_system/emulation_system/compose_file_creator/conversion/service_creation/emulator_proxy_creation.py
emulation_system/emulation_system/compose_file_creator/conversion/service_creation/input_service_creation.py
emulation_system/emulation_system/compose_file_creator/conversion/service_creation/shared_functions.py
emulation_system/emulation_system/compose_file_creator/conversion/service_creator.py
emulation_system/emulation_system/compose_file_creator/input/hardware_models/hardware_model.py
emulation_system/emulation_system/compose_file_creator/settings/images.py
emulation_system/tests/compose_file_creator/input/hardware_models/test_hardware_model.py

Split service_creation.py up into separate files
Add tests for image names

refactor: Refactor service creation

---

samples/json/ot2_and_heater_shaker.json
samples/yaml/ot2_and_heater_shaker.yaml

Add sample files for creating OT2 and Heater-Shaker together

chore: OT2 and Heater Shaker sample JSON and YAML files

---

samples/json/ot2_and_2_heater_shakers.json
samples/json/ot2_and_heater_shaker.json
samples/yaml/ot2_and_2_heater_shakers.yaml

chore: OT2 with 2 Heater Shakers

---

emulation_system/emulation_system/opentrons_emulation_configuration.py
emulation_system/tests/compose_file_creator/conversion_logic/conftest.py

Remove emulation-configuration-file-locations as it will not be used

chore: Remove unused property

---

Makefile

Remove duplicated EMULATION_SYSTEM_CMD

fix: Remove duplicated command

---

emulation_system/emulation_system/consts.py
emulation_system/tests/compose_file_creator/conftest.py
emulation_system/tests/compose_file_creator/conversion_logic/conftest.py
emulation_system/tests/compose_file_creator/conversion_logic/test_conversion_logic.py
emulation_system/tests/compose_file_creator/conversion_logic/test_environment_variables.py
emulation_system/tests/compose_file_creator/conversion_logic/test_extra_service_creation.py
emulation_system/tests/compose_file_creator/conversion_logic/test_system_unique_id.py
emulation_system/tests/compose_file_creator/input/hardware_models/modules/test_heater_shaker_module.py
emulation_system/tests/compose_file_creator/input/hardware_models/modules/test_magnetic_module.py
emulation_system/tests/compose_file_creator/input/hardware_models/modules/test_temperature_module.py
emulation_system/tests/compose_file_creator/input/hardware_models/modules/test_thermocycler_module.py
emulation_system/tests/compose_file_creator/input/hardware_models/robots/test_ot2.py
emulation_system/tests/compose_file_creator/input/test_configuration_file.py
emulation_system/tests/conftest.py

Remove unused fixtures and functions
Move fixtures to be as close to tests as possible. 
Only shared fixtures and functions in conftest files
None
None

chore: Cleanup fixtures and functions.

---

README.md
emulation_system/emulation_system/compose_file_creator/errors.py
emulation_system/emulation_system/compose_file_creator/output/runtime_compose_file_model.py
emulation_system/emulation_system/compose_file_creator/settings/images.py
emulation_system/tests/compose_file_creator/conversion_logic/test_bind_mounts.py

test: Robot server mount tests

---

Makefile

Remove vm commands from Makefile

chore: Remove VM commands

---

.github/workflows/emulation-system-lint-test.yaml

Cache Python dependencies, it speeds up the run from 1:45 to 0:48

chore: Cache python dependencies

---

.github/workflows/repo-action-validation.yaml

Change all action references to main

chore: Change all action references to main

---

.github/workflows/yaml-sub-sanity-check.yaml

Change yaml action ref to main

chore: Change ref to main

---

.github/actions/yaml-sub/action.yaml
.github/workflows/yaml-sub-sanity-check.yaml
action.yaml

Add output file location parameter

feat: Add output file location

---

Makefile
docker/Dockerfile
docker/entrypoint.sh
samples/ot3/ot3_local.yaml
scripts/rebuild_and_run_local_containers.sh

Add `em-local-rebuild` command
- Add `em-local-rebuild` make command
- Change the paths for C++ executables to be nicer
- Add stop commands to entrypoint.sh
- Add script `rebuild_and_run_local_containers.sh`
None
None

feat: Add nice automagical rebuild make command

---

docs/ARCHITECTURE.md

docs: OT3 Docker Architecture

---

README.md

chore: Update README Links

---

docs/ARCHITECTURE.md

chore: Reverse Colors

---

samples/ot2/ot2_with_modules_and_pipettes.yaml

Add sample file for utilizing custom pipettes

chore: Add sample file with custom pipettes

---

docs/ARCHITECTURE.md

Add docs and diagrams explaining paradigm for build artifacts

docs: Add architecture docs for build artifacts

---

Makefile
README.md
docs/team_specific_setup/CPX_SETUP.md
docs/team_specific_setup/OT3_FIRMWARE_DEVELOPMENT_SETUP.md
scripts/makefile/rebuilding.mk

Add evaluation of relative paths to Makefile. Update docs to reflect
@sfoster1 is there a less gross way then doing `$(realpath ${file_path})` everywhere?

chore: Support relative paths

---

README.md

Add detailed instructions for pyenv and pipenv setup

docs: Add in-depth instructions for installing pyenv and pipenv

---

.github/workflows/emulation-system-lint-test.yaml
.github/workflows/repo-action-validation.yaml
.github/workflows/test-samples-files.yaml
.github/workflows/yaml-sub-sanity-check.yaml

- Add run filters to yaml-sub-sanity-check and repo-action-validation
- Add name to yaml-sub-sanity-check and repo-action-validation
- Remove running on `opentrons-emulation` for emulation-system-lint-test as it no longer exists
- Remove extraneous comment

chore: Maintenance on Github Actions

---

.github/workflows/emulation-system-lint-test.yaml

chore: Add workflow dispatch input

---

README.md
RELEASE_NOTES.md

v2.1.0 Release Notes
Markdown Formatting

docs: V2.1.0 Release Notes

---

docker/Dockerfile
docker/entrypoint.sh
emulation_system/emulation_system/compose_file_creator/conversion/service_creation/ot3_service_creation.py
emulation_system/emulation_system/compose_file_creator/settings/config_file_settings.py
emulation_system/emulation_system/compose_file_creator/settings/container_filters.py
emulation_system/emulation_system/compose_file_creator/settings/images.py
samples/ot3/ot3_remote.yaml

Add bootloader simulator to OT3 emulator

feat: Add bootloader simulator to OT3 emulator

---

docker/Dockerfile
docker/entrypoint.sh
emulation_system/emulation_system/compose_file_creator/conversion/service_creation/ot3_service_creation.py
emulation_system/emulation_system/compose_file_creator/settings/config_file_settings.py
emulation_system/emulation_system/compose_file_creator/settings/container_filters.py
emulation_system/emulation_system/compose_file_creator/settings/images.py

Add gripper simulator to OT3 emulator

feat: Add gripper simulator to OT3 emulator

---

.github/actions/setup-break-cache/action.yaml
.github/actions/setup/action.yaml
.github/workflows/run-hardware-tests.yaml
action.yaml

Add running of opentrons hardware integration tests against ot3-firmware
Will add nightly schedule in subsequent PR

feat: Run ot3-firmware integration tests in CI

---

.github/workflows/run-hardware-tests.yaml

Meant to merge slack notifications into main. I didn't I merged them into `run-integration-tests-in-ci`. This PR is to clean that up

chore: Add Slack Webhook

---

README.md
docker/Dockerfile
docs/DOCKERFILE_ARCHITECTURE.md

Create Dockerfile Architecture Diagram

docs: Add Dockerfile Arch diagram

---

.github/actions/setup-python-only/action.yaml
.github/workflows/emulation-system-lint-test.yaml
.github/workflows/repo-action-validation.yaml
.github/workflows/run-hardware-tests.yaml
.github/workflows/yaml-sub-sanity-check.yaml
Makefile
scripts/makefile/helper_scripts/build.sh

- pipenv updated out from under me and broke everything. Set pipenv to hard 2022.1.8 version
- Had to update action refs to this branch to get them to run. Will update to main in subsequent PR. This process sucks and I want to find a better way
- Moved some comments around

fix: Fix broken Github Actions

---

docs/team_specific_setup/APPS_AND_UI_SETUP.md

chore: Fix README Formatting

---

README.md
action.yaml
docs/GITHUB_ACTION_DOCS.md

docs: Github Actions Docs

---

.github/actions/setup-python-only/action.yaml
.github/workflows/emulation-system-lint-test.yaml
.github/workflows/repo-action-validation.yaml
.github/workflows/run-hardware-tests.yaml
.github/workflows/test-samples-files.yaml
.github/workflows/yaml-sub-sanity-check.yaml
docker/Dockerfile
docker/entrypoint.sh

Run cmake --build with -j option to run it multithreaded
Has changes from https://github.com/Opentrons/opentrons-emulation/pull/142

feat: Run cmake multithreaded

---

.github/workflows/emulation-system-lint-test.yaml
.github/workflows/repo-action-validation.yaml
.github/workflows/run-hardware-tests.yaml
.github/workflows/test-samples-files.yaml
.github/workflows/yaml-sub-sanity-check.yaml

Change filtering to match https://github.com/Opentrons/opentrons/pull/9771

chore: Github Action Filtering

---

.github/workflows/emulation-system-lint-test.yaml
.github/workflows/repo-action-validation.yaml
.github/workflows/run-hardware-tests.yaml
.github/workflows/test-samples-files.yaml
.github/workflows/yaml-sub-sanity-check.yaml

Run workflows on main Makefile changes

chore: Run workflows on main Makefile changes

---

.github/workflows/emulation-system-lint-test.yaml
.github/workflows/repo-action-validation.yaml
.github/workflows/run-hardware-tests.yaml
.github/workflows/test-samples-files.yaml
.github/workflows/yaml-sub-sanity-check.yaml

Update action refs to main in prep for v2.2.0

chore: Update Action refs to main

---

RELEASING.md

Add release workflow documentation

docs: Release Workflow docs

---

docker/Dockerfile
docker/entrypoint.sh

Thermocycler Refresh is being renamed to Thermocycler Gen2. Account for that

chore: Thermocycler gen2 support

---

.github/workflows/repo-action-validation.yaml
.github/workflows/run-hardware-tests.yaml

Update refs to`release-v2.3.0`

chore: Update refs

---

.github/actions/setup-python-only/action.yaml
.github/workflows/repo-action-validation.yaml
.github/workflows/run-hardware-tests.yaml
.github/workflows/upload-docker-image-bases.yaml
Makefile
RELEASE_NOTES.md
docker/Dockerfile
docker/bases_Dockerfile
docker/build_bases.sh
docker/cache_helpers/GetClangAndBoost_CMakeLists.txt

chore: Release v2.3.0

---

docs/RELEASE_NOTES.md

docs: Changelog

---

Pipfile.lock
README.md

Revised the documentation to use Python 3.10.4, added in docker compose generate command & video of Derek's emulator demo setup.
- Revised the markdown file and Pipfiles to use 3.10.4
- Added video link of Derek's Maggio's Emulator setup.
- Added generate docker compose command for testing setup of Docker on Mac/Linux environments prior to build command.
None
Low

docs: Update README

---

README.md
docs/team_specific_setup/APPS_AND_UI_SETUP.md

Fixed typos in readme for app-ui env.
Also updated the branch name.
- update readme (APPS_AND_UI_SETUP.md)
- changes are correct 
low

Fix: fix typos in readme  for App-UI env

---

.github/workflows/emulation-system-lint-test.yaml
.github/workflows/repo-action-validation.yaml
.github/workflows/run-hardware-tests.yaml
.github/workflows/test-samples-files.yaml
.github/workflows/yaml-sub-sanity-check.yaml
Makefile
docker/Dockerfile
docker/entrypoint.sh
docs/EMULATION_CONFIGURATION_FILE_KEY_DEFINITIONS.md
docs/RELEASE_NOTES.md
emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/heater_shaker_module.py
emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/module_model.py
emulation_system/emulation_system/compose_file_creator/settings/config_file_settings.py
emulation_system/emulation_system/compose_file_creator/settings/images.py
emulation_system/tests/compose_file_creator/input/hardware_models/modules/test_heater_shaker_module.py
emulation_system/tests/compose_file_creator/input/hardware_models/test_hardware_model.py

Release v2.3.3
- Add Firmware Level Heater-Shaker Emulation support
- Fix load-containers makefile command
None
Low

chore: Release v2.3.3

---

docker/bases_Dockerfile

Make sure to latest version of pip (was running into bugs using older versions)

Use latest version of pip

---

.github/workflows/run-hardware-tests.yaml

I am going to turn this off until I get it fixed. It is just basically reminding me of my failures every morning in slack.

chore: Turn off Hardware Testing notifications

---

.github/workflows/emulation-system-lint-test.yaml
.github/workflows/repo-action-validation.yaml
.github/workflows/run-hardware-tests.yaml
.github/workflows/yaml-sub-sanity-check.yaml
emulation_system/emulation_system/compose_file_creator/conversion/service_builders/concrete_ot3_service_builder.py
samples/ot3/ot3_remote.yaml

Fix pipettes not loading correctly because no eeprom var was specified
- Add `EEPROM_FILENAME=eeprom.bin` env var
None
Low

fix: Fix Hardware Tests not working (RQA-258)

---

README.md

Documentation on compose-file-creator logging.

docs: Logging Documentation (RQA-257)

---

samples/ot3/ot3_remote_with_custom_robot_name.yaml

Add sample configuration for custom robot name

chore: Add sample configuration for custom robot name

---

Makefile

fix(python) we need to specify can-mon and can-com python version since we added 3.7

---

docker/build_bases.sh

chore: Fix build bases branch parsing

---

docker/entrypoint.sh

Remove stop commands from entrypoint.sh
These will be replaced with the local build refactor

chore: Remove stop commands from entrypoint.sh (RQA-380)

---

emulation_system/emulation_system/compose_file_creator/config_file_settings.py
emulation_system/emulation_system/compose_file_creator/input/hardware_models/hardware_specific_attributes.py
samples/ot2/ot2_and_2_heater_shakers.yaml
samples/ot2/ot2_and_heater_shaker.yaml
samples/ot2/ot2_local.yaml
samples/ot2/ot2_local_with_all_modules.yaml
samples/ot2/ot2_remote.yaml
samples/ot2/ot2_with_all_modules.yaml
samples/ot2/ot2_with_modules_and_pipettes.yaml
samples/ot3/ot3_local.yaml
samples/ot3/ot3_remote.yaml
samples/ot3/ot3_remote_with_custom_robot_name.yaml
samples/team_specific_setups/cpx_ot2.yaml
samples/team_specific_setups/ot3_firmware_development.yaml

Sample file updates for local dev refactor

chore: Sample File Changes

---

.github/workflows/emulation-system-lint-test.yaml
.github/workflows/run-hardware-tests.yaml
.github/workflows/yaml-sub-sanity-check.yaml

- Add concurrency
- Fix Yaml Substitution Github Action so it actually validates that it's working

chore: Rework CI

---

docker/entrypoint.sh
scripts/docker_convenience_scripts/create_dev_dockerfile.sh

Also update create_dev_dockerfile.sh:
- Update delimiter to pipe instead of semicolon (easier to read)
- Move syntax statement to beginning of created dev dockerfile

fix: Add server-utils project to monorepo build

---

emulation_system/emulation_system/compose_file_creator/input/hardware_models/robots/ot2_model.py
emulation_system/emulation_system/compose_file_creator/input/hardware_models/robots/ot3_model.py
emulation_system/emulation_system/compose_file_creator/input/hardware_models/robots/robot_model.py
emulation_system/tests/compose_file_creator/conversion_logic/test_conversion_logic.py
samples/ci/ot3/ot3_and_modules.yaml
samples/ci/ot3/ot3_remote.yaml
samples/ci/team_specific_setups/ot3_firmware_development.yaml
samples/ot2/ot2_and_2_heater_shakers.yaml
samples/ot2/ot2_and_heater_shaker.yaml
samples/ot2/ot2_local.yaml
samples/ot2/ot2_local_with_all_modules.yaml
samples/ot2/ot2_remote.yaml
samples/ot2/ot2_with_all_modules.yaml
samples/ot2/ot2_with_modules_and_pipettes.yaml
samples/ot3/ot3_local.yaml
samples/ot3/ot3_remote.yaml
samples/ot3/ot3_remote_with_custom_robot_name.yaml
samples/team_specific_setups/cpx_ot2.yaml
samples/team_specific_setups/ot3_firmware_development.yaml

Add defaults for robot server bound port and can server bound port
Update config files to remove any port definitions that specify the default port
Update config file descriptions
- Proofread of config file descriptions
Low

Update config defaults

---

Makefile
docker/Dockerfile
docker/entrypoint.sh
docker/entrypoints/monorepo_builder.sh
docker/entrypoints/ot3_firmware_builder.sh
docker/scripts/selective_monorepo_builder.sh
emulation_system/Makefile
emulation_system/emulation_system/compose_file_creator/conversion/service_builders/ot3_services.py
emulation_system/emulation_system/compose_file_creator/pipette_utils/data_models.py
emulation_system/emulation_system/compose_file_creator/pipette_utils/lookups.py
emulation_system/tests/compose_file_creator/conversion_logic/service_builders/test_concrete_ot3_service_builder.py
emulation_system/tests/compose_file_creator/test_pipette_utils.py
pipette_versions.json
samples/ci/ot3/ot3_and_modules.yaml
samples/ci/ot3/ot3_remote.yaml
samples/ci/team_specific_setups/ot3_firmware_development.yaml

Various fixes for supporting pipette provisioning script in monorepo
See [commits](https://github.com/Opentrons/opentrons-emulation/pull/263/commits)
None
Low

chore: Monorepo script compatability
