Opentrons/opentrons-emulation

- action.yaml
- scripts/run_emulation.sh
Changing name of `ot3-emulator` repo to `opentrons-emulation`. This PR will also allow providing of `latest` to the commit id to pull the latest commit from the main branch. Added this because we always have to specify the commit id option in Github Actions but sometimes we just want to specify latest
> chore: Allow for providing of default value

- emulation_system/emulation_system/settings_models.py
- emulation_system/resources/docker/Dockerfile
- emulation_system/resources/docker/docker-compose-dev.yaml
- emulation_system/resources/docker/docker-compose.yaml
- emulation_system/resources/docker/entrypoint.sh
- emulation_system/resources/vagrant/Vagrantfile
Added the following stages: 
- python-base
- opentrons-source
- driver-builder
- driver-common
Added the following images
- emulator-proxy-prod
- emulator-proxy-dev
- thermocycler-driver-prod
- thermocycler-driver-dev
- magdeck-driver-prod
- magdeck-driver-dev
- tempdeck-driver-prod
- tempdeck-driver-dev
- Added python-base target. This is the base for all driver-level emulators and the emulator-proxy
- Installs all python and node stuff required for building and running our projects
- Refactored cpp-base and ubuntu-base. Pulled any dependencies that are in both cpp-base and python-base and added them to ubuntu-base
- Added opentrons-source target. This pulls code from [opentrons repo](https://github.com/Opentrons/opentrons) 
- Added driver-builder target. This builds the code that we …
> feat: Add driver level emulator images

- emulation_system/resources/docker/Dockerfile
This is required by new codegen in ot3-firmware. The firmware repo will
set up everything but the interpreter itself.
> feat: add python to cpp-base

- emulation_system/resources/docker/Dockerfile
Fix error happening when trying to install poetry. [Error](https://github.com/Opentrons/ot3-firmware/runs/4410588901?check_suite_focus=true)
During investigation I tried running `/bin/sh -c "python install-poetry.py`. This the command `cmake` is running to install poetry, I received an error saying I needed to install python virtual environments. So I added the command to do that to the Dockerfile
- Add python3.7-venv to list of packages to install
None. This should work just fine. 
I tested manually by building firmware container with custom compose file and then running the build inside the container
But I will test further when I have the fixes in to allow ot3-firmware to build the emulator again
None, it's already broken in ot3-firmware.
> fix: Fix poetry not installing correctly

- emulation_system/emulation_system/compose_file_creator/input/configuration_file.py
- emulation_system/tests/compose_file_creator/input/hardware_models/test_hardware_model.py
- emulation_system/tests/compose_file_creator/input/test_configuration_file.py
- emulation_system/tests/conftest.py
- emulation_system/tests/test_resources/invalid_configurations/invalid_name_format.json
- emulation_system/tests/test_resources/invalid_configurations/matching_module_names.json
- emulation_system/tests/test_resources/invalid_configurations/matching_robot_and_module_names.json
- emulation_system/tests/test_resources/sample.json
- emulation_system/tests/test_resources/valid_configurations/empty_modules_key.json
- emulation_system/tests/test_resources/valid_configurations/empty_robot_key.json
- emulation_system/tests/test_resources/valid_configurations/modules_only.json
- emulation_system/tests/test_resources/valid_configurations/robot_and_modules.json
- emulation_system/tests/test_resources/valid_configurations/robot_only.json
Change input file format to only support a single robot
Changed format of configuration file. 
- The `robot` entry is now a dictionary containing all the information about a single robot.
- The `modules` entry is now a list of `Modules` objects
- The `id` key will now how to specified for all hardware
- Modified `validate_names` `root_validator` to account for changes to format
- Added `DuplicateHardwareNameErro`r that is thrown instead of just a normal `ValidationError`
- Removed `there_can_only_be_one`, `add_robot_ids`, and `add_module_ids` validators as they are no longer necessary
- Modified `modules_exist`, `robot_exists`, and containers methods to account for change to format
- Removed `get_robot` method as it is now just a singular value
Tests
- Pulled verbose fixtures from …
> refactor: Only support one robot

- emulation_system/emulation_system/compose_file_creator/input/configuration_file.py
- emulation_system/tests/compose_file_creator/input/test_configuration_file.py
- emulation_system/tests/test_resources/valid_configurations/null_version.json
- emulation_system/tests/test_resources/valid_configurations/version_def.json
Added ability to specify compose file version in input file
- Added string `compose_file_version` parameter to SystemConfigurationModel
- Added validator to set version if nothing is specified
- Added tests
None
Low
> feat: Compose version (RET-394)

- emulation_system/emulation_system/compose_file_creator/conversion/conversion_functions.py
- emulation_system/emulation_system/opentrons_emulation_configuration.py
- emulation_system/emulation_system/parsers/top_level_parser.py
- emulation_system/main.py
- emulation_system/tests/command_creators/test_emulation.py
- emulation_system/tests/command_creators/test_virtual_machine.py
- emulation_system/tests/compose_file_creator/test_conversion_logic.py
- emulation_system/tests/conftest.py
Add logic for loading emulation configuration files from locations specified in emulation-configuration-file-locations
- Add `load_opentrons_emulation_configuration` to [opentrons_emulation_configuration.py](https://github.com/Opentrons/opentrons-emulation/pull/54/files#diff-18d96ae170acc31b8fe7ea29bcb16dec18438019e2887ebc683ab14d08da5461)
- Modify top_level_parser to use `load_opentrons_emulation_configuration`
- Add conversion logic in convert_from_file
- Add tests
Is there a better way to do this setup 
https://github.com/Opentrons/opentrons-emulation/pull/54/files#diff-749708e38c60613f39be1142cb867f721f9d31ad51840431e08edf52869f8ac7R80-R114
Low
> feat: Add logic for loading files from multiple locations

- emulation_system/emulation_system/compose_file_creator/conversion/service_creator.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/robots/ot2_model.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/robots/robot_model.py
- emulation_system/tests/compose_file_creator/conftest.py
- emulation_system/tests/compose_file_creator/input/hardware_models/robots/test_ot2.py
- emulation_system/tests/compose_file_creator/test_conversion_logic.py
Add logic for exposing robot port
- [robot_model.py](https://github.com/Opentrons/opentrons-emulation/pull/55/files#diff-435ac9a915b872f05ff4d9816cab0182f12aaa7396e247fa6d7a0245245c3a22)
- Change `RobotModel` to `RobotInputModel` for consistency with other classes
- Add `exposed_port` and `bound_port` properties to `RobotInputModel`
- Add `get_port_binding_string` method
- [conftest.py](https://github.com/Opentrons/opentrons-emulation/pull/55/files#diff-01fc315b59882da252ab2cfe360f6ec8327ca1105b27688c32bc00982bec1fcf)
- Add setup for setting `exposed_port` and overriding `bound_port`
- [ot2_model.py](https://github.com/Opentrons/opentrons-emulation/pull/55/files#diff-2a137b5dfd13bec19697db1ab918f1f0b587c5cecee313e889555e5c176d1960)
- Define default for `bound_port` in `OT2InputModel`
- …
> feat: Robot exposed port (RET-428)

- emulation_system/emulation_system/compose_file_creator/conversion/service_creator.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/heater_shaker_module.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/magnetic_module.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/module_model.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/temperature_module.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/thermocycler_module.py
- emulation_system/tests/compose_file_creator/test_conversion_logic.py
Add functionality to populate environment variable for serial number.
- [module_model.py](https://github.com/Opentrons/opentrons-emulation/pull/58/files#diff-0f98439172f71cadc1b2b4af1a21b0637c96fcafab77045e9b4be78a121a7851)
- Created FirmwareSerialNumberModel
- Add logic for generating either firmware level or hardware level serial number env var
- ModuleInputModule classes
- Define firmware_serial_number_info
- Note for Heater Shaker that it is defaulted to `None` because there is no firmware level emulation implementation 
- Add test
Does the ClassVar stuff for firmware_serial_number_info need some comments to talk about what it is doing?
None
> feat: Serial Number Environment Variable Creation (RET-427)

- emulation_system/emulation_system/compose_file_creator/conversion/service_creator.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/heater_shaker_module.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/magnetic_module.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/module_model.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/temperature_module.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/thermocycler_module.py
- emulation_system/tests/compose_file_creator/test_conversion_logic.py
Add Emulator Proxy connection environment variables to modules and Emulator Proxy itself.
Parameterize serial number tests
- [service_creator.py](https://github.com/Opentrons/opentrons-emulation/pull/59/files#diff-2c156182f7bf5f2c2c6e11912fa49a4d369e664279af1a5f56960da26e28048b)
- Add `_create_emulator_proxy_env_vars` method to add all connection env vars to emulator proxy
- Add `container.get_proxy_info_env_var` call inside all Module containers
- [module_model.py](https://github.com/Opentrons/opentrons-emulation/pull/59/files#diff-0f98439172f71cadc1b2b4af1a21b0637c96fcafab77045e9b4be78a121a7851)
- Add `ProxyInfoModel` class to describe proxy connection
- Define proxy_info class variable, provide instantiation on all modules
- TESTING!!!
None
None
> feat: Add Emulation Proxy Connection Environment Variables (RET-426)

- emulation_system/emulation_system/compose_file_creator/conversion/service_creation/input_service_creation.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/hardware_model.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/heater_shaker_module.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/magnetic_module.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/module_model.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/temperature_module.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/thermocycler_module.py
- emulation_system/tests/compose_file_creator/conversion_logic/test_conversion_logic.py
Add custom command for heater-shaker and thermocycler when used at hw level.
- Add `get_hardware_level_command` and `get_firmware_level_command` to [hardware_model.py](https://github.com/Opentrons/opentrons-emulation/pull/65/files#diff-23187c61c270d5135c350f4faed79b015900d428c9f04c28ab15a9dcf102bc540)
- Add overrides where needed 
- Update tests
None
Low
> fix: Add logic to allow setting command based on em level and hardware

- Makefile
- README.md
Add compatibility for Mac M1
- Use `buildx bake` to change all plaforms to `x86_64` for M1 Mac
- Update README
Test on Linux (Derek), Intel Mac (Amit), and ARM Mac (Derek and Josh)
None
> feat: Mac M1 compatability

- emulation_system/emulation_system/compose_file_creator/conversion/service_creation/ot3_service_creation.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_creation/shared_functions.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_creation/smoothie_service_creation.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/hardware_model.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/robots/robot_model.py
- emulation_system/tests/compose_file_creator/conftest.py
- emulation_system/tests/compose_file_creator/conversion_logic/test_extra_service_creation.py
- samples/yaml/ot2_local.yaml
- samples/yaml/ot2_remote.yaml
- samples/yaml/ot3_local.yaml
- samples/yaml/ot3_remote.yaml
- In robot-server, remove source code mounts that are meant for emulator only
- In smoothie and ot3 emulators, remove source code mounts that are meant for robot-server only
- Add entrypoint.sh mount if anything else is mounted. (Scoping it like this is a little broad, but it doesn't hurt anything)
Look at the commits, I broke up individual changes into their own commits. 
None
Low
> fix: Remove extraneous mounts (RET-496, RET-497 RET-498)

- CPX_SETUP.md
- docker/entrypoint.sh
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/robots/robot_model.py
- samples/yaml/ot2_local_with_all_modules.yaml
Add configuration for CPX to use emulation
- Create configuration for CPX. `samples/yaml/ot2_local_with_all_modules.yaml`
- Fix robot server not using `robot_server_source_type` when looking for what image to use
- Fix up `entrypoint.sh` to get uvicorn to rebuild correctly
1. Follow instructions in [README](https://github.com/Opentrons/opentrons-emulation/blob/configuration_for_cpx/README.md) for initial setup
2. Go into `samples/yaml/ot2_local_with_all_modules.yaml` and replace the value for `robot.robot-server-source-location` with a path to your mono repo
3. From the root of the repo run `make em-build-amd64 file_path=${PWD}/samples/yaml/ot2_local_with_all_modules.yaml`. This will take forever for the intial build, probably around 10 minutes.
4. From the root of the repo run `make …
> chore: Configuration for cpx

- Makefile
- emulation_system/emulation_system/commands/emulation_system_command.py
- emulation_system/emulation_system/compose_file_creator/conversion/conversion_functions.py
- emulation_system/emulation_system/compose_file_creator/errors.py
- emulation_system/emulation_system/compose_file_creator/input/configuration_file.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/hardware_model.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/robots/ot3_model.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/robots/robot_model.py
- emulation_system/emulation_system/compose_file_creator/output/runtime_compose_file_model.py
- emulation_system/emulation_system/parsers/emulation_system_parser.py
- emulation_system/tests/command_creators/test_emulation_system.py
- emulation_system/tests/compose_file_creator/conversion_logic/test_source_code_insertion.py
Add `check-remote-only` Makefile command to confirm that all emulators in passed config file are remote.
This is in prep for creating a Github Action where it is required that all the source types for emulators are remote
See commits
None
Low
> feat: Add check-remote-only makefile command

- .github/actions/run/action.yaml
- .github/actions/setup-break-cache/action.yaml
- .github/actions/setup/action.yaml
- .github/actions/teardown/action.yaml
- .github/workflows/repo-action-validation.yaml
- action.yaml
Created public Github Action for use in other repositories
- There are now 4 local actions inside `.github/actions/`:
- `setup` - Get all dependencies and build docker images
- `setup-break-cache` - Same as above but does not use cache (For debugging)
- `run` - Start emulation Docker containers
- `teardown` - Remove emulation Docker containers
- There is now an `action.yaml` in the root of the repository
- This action takes an `input-file` and `command` parameter
- The input file must match the format from this repository. See [samples](https://github.com/Opentrons/opentrons-emulation/tree/main/samples) for more info
- Takes one of the above commands
- Refactor `repo-action-validation.yaml` to use public actions
None
Low
> feat: Create Public Github Action for Repository

- .github/actions/setup-python-only/action.yaml
- .github/actions/setup/action.yaml
- .github/actions/yaml-sub/action.yaml
- .github/workflows/repo-action-validation.yaml
- .github/workflows/yaml-sub-sanity-check.yaml
- action.yaml
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/heater_shaker_module.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/magnetic_module.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/temperature_module.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/thermocycler_module.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/robots/ot2_model.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/robots/ot3_model.py
- emulation_system/emulation_system/compose_file_creator/utilities/__init__.py
- emulation_system/emulation_system/compose_file_creator/utilities/substitute_yaml_values.py
- emulation_system/tests/compose_file_creator/utilities/__init__.py
- emulation_system/tests/compose_file_creator/utilities/test_substitute_yaml_values.py
Add Github action `yaml-sub` to make substitutions to `opentrons-emulation` configuration file
- Factor out Python only setup into `setup-python-only` action
- Add `yaml-sub` action
- Add `yaml-sub-sanity-check.yaml`
- Add `exclude=True` to all source_repo fields so they are not included in export of SystemConfigurationModel
- Fix mode rendering in HeaterShakerModuleInputModel
- Add substitute_yaml_values.py script
- Add tests for above
None
Low
> feat: Add yaml-sub Github Action

- Makefile
- emulation_system/emulation_system/compose_file_creator/conversion/conversion_functions.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_creation/can_server_creation.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_creation/ot3_service_creation.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_creation/shared_functions.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_creation/smoothie_service_creation.py
- emulation_system/tests/compose_file_creator/conversion_logic/test_source_code_insertion.py
- scripts/rebuild_and_run_local_containers.sh
Store build artifacts in shared named volumes.
This prevents conflicts in ot3-firmware when building on a Mac. Previously all firmware dependencies were bound into the container. Well the containers are Linux containers, so if you are a Mac you were binding in Mac specific dependencies and everything failed. 
Now all artifacts are stored in shared volumes that stand in place for the build artifact folders that are bound in
- Exposed 3 new functions in shared_functions.py:
- `add_ot3_firmware_named_volumes`
- `add_opentrons_named_volumes`
- `add_opentrons_modules_named_volumes`
- Based on the source code repo, one of the above functions is called to add a named volume that overlaps with the build artifact directories for the repo
- Added generating top level volume designations in …
> feat: Add build artifact storage to system

- emulation_system/emulation_system/compose_file_creator/input/hardware_models/robots/ot2_model.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/robots/ot3_model.py
- emulation_system/tests/compose_file_creator/input/hardware_models/robots/test_ot2.py
When passing custom pipettes to smoothie they were being ignore. 
The custom pipettes were expecting to be called `left` and `right`. They were being called `left-pipette` and `right-pipettes`.
Changed pydantic model so they were exported correctly
> fix: Custom Pipettes being ignored

- .github/actions/setup/action.yaml
- Makefile
- README.md
- docs/team_specific_setup/CPX_SETUP.md
- docs/team_specific_setup/OT3_FIRMWARE_DEVELOPMENT_SETUP.md
- scripts/makefile/helper_scripts/build.sh
Refactor `build-amd64` and `build-arm64` into single build command. 
Update docs and Github Actions
> refactor: Refactor build commands into a single multi-arch command

- Makefile
- emulation_system/emulation_system/commands/load_containers_command.py
- emulation_system/emulation_system/parsers/load_containers_parser.py
Fix bug where if can-server was built from a remote source you could not run `can-mon` or `can-comm` Makefile commands against it.
* Rename `load-local-containers ` cli command to `load-containers` and add a --local-only flag
* Add `load-containers` Makefile command
* Refactor `can-comm` and `can-mon` to use `load-containers` instead of `local-load-containers`
* Added `remove-build-run`, `remove-build-run-detached`, and `logs-follow` convenience commands
None
Low
> fix: Change can-comm and can-mon to look at remote and local containers

- .github/actions/setup-python-only/action.yaml
- .github/workflows/emulation-system-lint-test.yaml
- .github/workflows/repo-action-validation.yaml
- .github/workflows/yaml-sub-sanity-check.yaml
- Makefile
- action.yaml
- docs/team_specific_setup/OT3_FIRMWARE_DEVELOPMENT_SETUP.md
- emulation_system/emulation_system/compose_file_creator/conversion/service_creation/can_server_creation.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/robots/ot3_model.py
- emulation_system/tests/compose_file_creator/conversion_logic/test_conversion_logic.py
- samples/team_specific_setups/ot3_firmware_development.yaml
Add ability to expose port to can-server in docker
This is in preparation for running ot3-firmware integration in CI
> feat: Add can server exposed port

- .github/workflows/repo-action-validation.yaml
- .github/workflows/test-samples-files.yaml
- .github/workflows/yaml-sub-sanity-check.yaml
- scripts/makefile/helper_scripts/build.sh
- scripts/makefile/helper_scripts/get_untranslated_arch.sh
Add script to check if arch has been translated to x86_64
@y3rsh can you confirm this works for you?
I have confirmed that this works on Linux, and Mac M1 not running the shell in rosetta.
CI will cover the rest
> fix: Add handling for if your shell is running inside Rosetta

- docker/entrypoint.sh
The pipettes simulator location has changed since we are now compiling the firmware based on pipette
type.
- change pipettes simulator path in the entrypoint script
Let me know if there is any location I missed, and also whether I now need to bust the cache once this has merged.
Low.
> refactor(ot3-pipettes): modify path to pipettes simulator

- .github/workflows/run-hardware-tests.yaml
Add scheduled runs of hardware tests so they run Mon-Friday at 1:37 AM
`Running at 1:37 AM, so we don't get delays from so many people running nightly actions at midnight/top of hour`
> feat: Add scheduled runs of hardware tests

- .github/workflows/emulation-system-lint-test.yaml
- README.md
Add status badges to README. 
Add docs to `emulation-system-lint-test` workflow so the docs can be validated
> chore: Add fun status badges

- .github/workflows/run-hardware-tests.yaml
Update `run-hardware-tests` Github Action to only send messages on failure. 
https://github.com/Opentrons/opentrons-emulation/pull/151/commits/90c42acec7c237a7ba98f13f85b5e82ae0a18d4c forced a failure to make sure a message was sent.
https://github.com/Opentrons/opentrons-emulation/pull/151/commits/5c2ee65a84beefc85dd183cc1d2ea611d629124a and https://github.com/Opentrons/opentrons-emulation/pull/151/commits/b37abc4865cd4ea7eaa9d5efab68f673a1b49873 prove that the send message step is skipped on success
> chore: Only send slack message on failure for hardware tests

- .github/workflows/emulation-system-lint-test.yaml
- .github/workflows/repo-action-validation.yaml
- .github/workflows/run-hardware-tests.yaml
- .github/workflows/test-samples-files.yaml
- .github/workflows/yaml-sub-sanity-check.yaml
Remove all filters on `push` of all workflows in `opentrons-emulation`
Want to only run on any push to main or release branches.
Goal is to run all actions on push to main and release branches. 
Then filter what actions are ran on PR
> chore: Remove push filters on all workflows

- docker/entrypoint.sh
nproc arithmetic was not being evaluated correctly on Mac. Fixed it
Run `make build file_path=samples/ot3/ot3_remote.yaml` and `make build file_path=samples/ot2/ot2_with_all_modules.yaml` make sure they complete successfully
Low
> fix: Fix nproc arithmetic that was failing on Mac

- .github/actions/setup-python-only/action.yaml
- .github/workflows/repo-action-validation.yaml
- .github/workflows/run-hardware-tests.yaml
- .github/workflows/upload-docker-image-bases.yaml
- Makefile
- docker/Dockerfile
- docker/bases_Dockerfile
- docker/build_bases.sh
- Cache `ubuntu-base`, `cpp-base`, and `python-base` in Github Container Registry
- Add caching improvements to Github Actions 
- Split Dockerfile into `bases_Dockerfile` and `Dockerfile`
- `bases_Dockerfile` contains information for building `ubuntu-base`, `cpp-base`, and `python-base`
- `Dockerfile` contains everything else
- Add `build_bases.sh` script to push bases to Github Container Registry
- Add `upload-docker-image-bases.yaml` which builds and pushes bases to registry on update to `upload-docker-image-bases.yaml`, `bases_Dockerfile`, or `build_bases.sh`
- Add `push-docker-image-bases` Makefile target
- Add caching if statement to setup-python-only action
- Add caching of `hardware` project to `Run Hardware Tests` action
Try to build with this branch and see if it works. Nothing …
> feat: Github Container Repository Image Caching

- Makefile
Fix `load-container-names` Makefile Target.
When running `main.py` `load-container-names` is not a valid command. It is either `load-containers` or `lc`
> fix: Fix load-container-names Makefile Target

- docker/Dockerfile
- docker/entrypoint.sh
- docs/EMULATION_CONFIGURATION_FILE_KEY_DEFINITIONS.md
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/heater_shaker_module.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/module_model.py
- emulation_system/emulation_system/compose_file_creator/settings/config_file_settings.py
- emulation_system/emulation_system/compose_file_creator/settings/images.py
- emulation_system/tests/compose_file_creator/input/hardware_models/modules/test_heater_shaker_module.py
- emulation_system/tests/compose_file_creator/input/hardware_models/test_hardware_model.py
Enable opentrons-emulation to build and run the Heater-Shaker Firmware Emulator added in [this PR](https://github.com/Opentrons/opentrons/pull/11207)
- Add `heater-shaker-firmware-remote` and `heater-shaker-firmware-local` docker images
- Modify HeaterShakerModuleInputModel to support firmware images
- Add run commands to entrypoint
- Update README
None
> feat: Firmware Level Heater-Shaker Emulation

- .github/workflows/emulation-system-lint-test.yaml
- .github/workflows/repo-action-validation.yaml
- .github/workflows/run-hardware-tests.yaml
- .github/workflows/test-samples-files.yaml
- .github/workflows/yaml-sub-sanity-check.yaml
chore: Update GitHub Actions OS to Ubuntu 20.04
- The failing hardware tests have nothing to do with upgrading to 20.04. They are the same failures as before upgrading
> chore: Update GitHub Actions OS to Ubuntu 20.04

- .github/workflows/emulation-system-lint-test.yaml
- .github/workflows/repo-action-validation.yaml
- .github/workflows/run-hardware-tests.yaml
- .github/workflows/test-samples-files.yaml
- .github/workflows/yaml-sub-sanity-check.yaml
- Makefile
- docker/Dockerfile
- docker/entrypoint.sh
- docs/EMULATION_CONFIGURATION_FILE_KEY_DEFINITIONS.md
- docs/RELEASE_NOTES.md
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/heater_shaker_module.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/module_model.py
- emulation_system/emulation_system/compose_file_creator/settings/config_file_settings.py
- emulation_system/emulation_system/compose_file_creator/settings/images.py
- emulation_system/tests/compose_file_creator/input/hardware_models/modules/test_heater_shaker_module.py
- emulation_system/tests/compose_file_creator/input/hardware_models/test_hardware_model.py
Reverting due to some pipenv issues happening on initial runs of the `Run Hardware Tests` Github Action 
[Issue Example](https://github.com/Opentrons/opentrons-emulation/runs/8018300886?check_suite_focus=true)
> chore: Revert release-v2.3.3 due to Github Action Issues

- scripts/makefile/helper_scripts/get_untranslated_arch.sh
This PR fixes some shell syntax in `get_untranslated_arch.sh`.
I was getting this error when I did `make build`:
```
opentrons-emulation/scripts/makefile/helper_scripts/get_untranslated_arch.sh: line 10: [: ==: unary operator expected
```
The problem, I think, was that `sysctl -in sysctl.proc_translated` on my non-M1 Mac has no output. That caused this:
```
[ $(sysctl -in sysctl.proc_translated) == "1" ]
```
To get expanded as this:
```
[ == "1" ]
```
Which is a `[ ]` syntax error.
Switch from `[ ]` to `[[ ]]`, which will expand the `$(...)` to an empty string that can be `==`-compared as we expect.
* Does this continue to work as expected on an M1 Mac?
* I'm far from an expert on shell syntax. Does this look like the appropriate fix?
> fix: Fix operand expansion in get_untranslated_arch.sh

- .devcontainer/devcontainer.json
Forgot to add this.  Without it when VSCode opens the container it will use the user `vscode` and then lots of things don't work.
None, devcontainer only.
> fix(devcontainer): always root in devcontainer

- .github/workflows/emulation-system-lint-test.yaml
- .github/workflows/repo-action-validation.yaml
- .github/workflows/run-hardware-tests.yaml
- .github/workflows/yaml-sub-sanity-check.yaml
- Makefile
- README.md
- docker/Dockerfile
- docker/entrypoint.sh
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/concrete_ot3_service_builder.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/robots/ot3_model.py
- emulation_system/emulation_system/compose_file_creator/logging/ot3_logging_client.py
- emulation_system/tests/compose_file_creator/conftest.py
- emulation_system/tests/compose_file_creator/conversion_logic/service_builders/test_concrete_ot3_service_builder.py
- emulation_system/tests/compose_file_creator/conversion_logic/test_source_code_insertion.py
- emulation_system/tests/compose_file_creator/utilities/test_substitute_yaml_values.py
- samples/ot3/ot3_remote.yaml
Changes to make opentrons-emulation compatible with [ot3-firmware Header Creation Script](https://github.com/Opentrons/ot3-firmware/pull/435).
**Header Creation Script Compatability**
* Dockerfile
* Add monorepo installation to `ot3-firmware-source` build stage, since monorepo is now a dependency of ot3-firmware
* Add `opentrons-hardware-source-type` and `opentrons-hardware-source-location` to ot3 configuration
* Add mounting of monorepo for local ot3 containers
* Add monorepo build args for remote ot3 containers
* Add tests for local and remote ot3 containers
* Confirming that when `opentrons-hardware-source-type` is local, monorepo bind mounts are added
* Confirming that when `opentrons-hardware-source-type` is remote, monorepo build args are added
**Misc**
* Move creating dev …
> refactor: OT-3 Firmware Header Creation Script Compatability (RQA-219)

- Makefile
- docker/Dockerfile
- docker/bases_Dockerfile
- docker/entrypoint.sh
The commands `can-mon` and `can-comm` were trying to use pipenv to run. 
Inside the containers, pipenv is not used to install monorepo modules. 
Instead, the monorepo modules are installed directly using `python -m pip`. `python` is mapped to the version of python installed by `opentron-emulation`.
So instead of using `pipenv run python` just call `python` directly to run the internal commands
**Misc Changes**
* Edit and `pip` calls to use `python -m pip`
* Default shell to bash
* Remove symlink binding `python` and `python3` to system versions of python and bind them to installed version of python
* Install pipenv against installed version of python
* Change cpp-base to be built from python-base instead of ubuntu-base
1. Started an emulated OT-3 using `make dev-build` and `make …
> fix: Fix can-mon and can-comm commands (RQA-224)

- samples/ot3/ot3_local.yaml
- samples/team_specific_setups/ot3_firmware_development.yaml
This adds the opentrons-hardware source type and location to the `team_specific_setups/ot3_firmware_development.yaml`
> fix: Update team spec ot3 yaml file

- .github/workflows/emulation-system-lint-test.yaml
- .github/workflows/repo-action-validation.yaml
- .github/workflows/run-hardware-tests.yaml
- .github/workflows/yaml-sub-sanity-check.yaml
- README.md
- docker/bases_Dockerfile
- emulation_system/emulation_system/compose_file_creator/conversion/conversion_functions.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/abstract_service_builder.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/concrete_can_server_service_builder.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/concrete_emulator_proxy_service_builder.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/concrete_input_service_builder.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/concrete_ot3_service_builder.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/concrete_smoothie_service_builder.py
- emulation_system/emulation_system/compose_file_creator/errors.py
- emulation_system/emulation_system/compose_file_creator/input/configuration_file.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/magnetic_module.py
- emulation_system/emulation_system/compose_file_creator/output/compose_file_model.py
- emulation_system/emulation_system/compose_file_creator/types/final_types.py
- emulation_system/emulation_system/compose_file_creator/types/intermediate_types.py
- emulation_system/emulation_system/compose_file_creator/utilities/hardware_utils.py
- emulation_system/tests/command_creators/test_emulation_system.py
- emulation_system/tests/compose_file_creator/conversion_logic/service_builders/test_concrete_emulator_proxy_service_builder.py
- emulation_system/tests/compose_file_creator/conversion_logic/test_conversion_logic.py
- emulation_system/tests/compose_file_creator/conversion_logic/test_healthcheck.py
- emulation_system/tests/compose_file_creator/input/test_configuration_file.py
Add healthchecks to all emulator Docker containers
[Docker Healthcheck Documentation](https://docs.docker.com/compose/compose-file/#healthcheck)
- Add `net-tools` to ubuntu-base
- Add `generate_healthcheck` abstract method to AbstractServiceBuilder
- Implement `generate_healthcheck` for all ConcreteServiceBuilder` classes
- Remove `compose-file-version` field from input files. No longer specifying a version so that we can use [Docker Compose Specification](https://docs.docker.com/compose/compose-file/)
- Fix magdeck env variable so that it is actually used by underlying emulator
- Update existing tests to allow for healthcheck changes
- Add specific tests for healthcheck
None
Low
> feat: Add healthchecks to all containers (RQA-312)

- .github/workflows/emulation-system-lint-test.yaml
- .github/workflows/repo-action-validation.yaml
- .github/workflows/run-hardware-tests.yaml
- .github/workflows/yaml-sub-sanity-check.yaml
- samples/ot3/ot3_local.yaml
- samples/team_specific_setups/ot3_firmware_development.yaml
- scripts/makefile/helper_scripts/test_samples.sh
The Test All Sample Files Github Action, is not able to find the samples folder, yet still passes the Github Action. 
1. Change path so samples folder can be found 
2. If for some reason samples folder cannot be found, fail the tests
1. Fix all `local` configuration files to have paths that will be valid in CI
2. Update test_samples.sh
1. Fix path to `samples` folder
2. If `samples` folder is not found, exit with exit code 1
3. Format README
Anything else I am missing in [test_samples.sh](https://github.com/Opentrons/opentrons-emulation/blob/cbc3da3621a56530f25975243a4e772f7cbf1ccc/scripts/makefile/helper_scripts/test_samples.sh)?
Super super low
> fix: Fix "Test Sample Files" Github Action (RQA-311)

- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/concrete_ot3_service_builder.py
- emulation_system/tests/compose_file_creator/conversion_logic/service_builders/test_concrete_ot3_service_builder.py
Added `EEPROM_FILENAME` environment variable so the gripper emulator will work with robot-server.
- Add `EEPROM_FILENAME` environment variable with the value of `eeprom.bin` to gripper emulator
- Update tests
None
Low.
Tested against code in https://github.com/Opentrons/ot3-firmware/pull/461 and the OT-3 emulator now starts up.
> chore: Add gripper EEPROM_FILENAME environment variable

- README.md
Since we are no longer using pipenv one of the badges broke
> chore: Update broken badge

- docker/bases_Dockerfile
- samples/ot3/ot3_remote.yaml
Fix ubuntu-base-arm64 Docker Image being built against x86_64
- Change `${BUILDPLATFORM}` to `${TARGETPLATFORM}`. 
- What was happening was the system was setup to pull down an Ubuntu image with the same architecture as what the host platform was. Since we using a Linux runner to build both the ARM and x86_64 image, it was using the x86_64 version of Ubuntu to build ubuntu-base-arm64 which is obviously incorrect
- Remove hardcoded sha in ot3_remote.yaml
- Was failing to push packages in the `Upload Docker Image Bases` Github Action due to a 403 error. Had to go in to the package settings for `ubuntu-base-amd64`, `ubuntu-base-arm64`, `cpp-base-amd64`, and `cpp-base-arm64` and change it to allow `opentrons-emulation` to read and write the packages
None
Low, I pulled down all the images and …
> fix: Fix ubuntu-base-arm64 being built against x86_64

- .github/workflows/emulation-system-lint-test.yaml
- .github/workflows/repo-action-validation.yaml
- .github/workflows/run-hardware-tests.yaml
- .github/workflows/test-samples-files.yaml
- .github/workflows/yaml-sub-sanity-check.yaml
Fixing ref logic in Github Actions so it won't be necessary to be updating the refs for every PR.
- Any checkout of `opentrons-emulation` has been changed to `${{ github.sha }}` to pull the latest commit for the current branch.
- Any call to the `opentrons-emulation` Github Action will reference `main` unless editing `action.yaml` or any files in `.github/actions`. 
- Change run conditions for `Run Hardware Tests` Github action. Only run if action anything related to actions is being changed and on schedule. Not gaining anything by running it otherwise. 
- Turn Slack notifications for `Run Hardware Tests` back on
- Change committing model to merge to `main` and any releases will just be a tagged commit on `main`
None
Low
> chore: Parameterize Github Action Refs

- docker/bases_Dockerfile
- docker/entrypoint.sh
Monorepo was not building against python3.7
Now it is.
- Install Python 3.7 into ubuntu-base
- Symlink it as `monorepo_python`
- Symlink Python 3.8 as `state_manager_python`
None
Low, it's already broken
> fix: Build monorepo against python3.7

- docker/entrypoint.sh
Changes how the ip address for the state manager is passed from `entrypoint.sh`. This is necessary to allow the state manager to receive any UDP traffic through Docker.
Tested on a local setup. Without this, it is impossible to send a message to the state manager and get a response. With this change, I can send UDP messages and get responses.
* Changed the state manager IP address designation from `localhost` to `0.0.0.0`
Minimal, this was already broken and the state manager is disabled right now.
> fix: changed specification of state manager IP

- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/abstract_service_builder.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/concrete_input_service_builder.py
- emulation_system/emulation_system/compose_file_creator/logging/input_logging_client.py
- emulation_system/emulation_system/compose_file_creator/output/compose_file_model.py
- emulation_system/emulation_system/compose_file_creator/types/final_types.py
- emulation_system/emulation_system/compose_file_creator/types/intermediate_types.py
- emulation_system/tests/compose_file_creator/conversion_logic/test_depends_on.py
Containers that depend on emulator-proxy now wait for it to be healthy before starting
- Update depends_on logic to include conditions
- Update tests
None
Low, it was already broken
> fix: Make containers wait for emulator-proxy to be healthy before starting (RQA-340)

- docker/Dockerfile
- docker/entrypoints/local_ot3_firmware_builder.sh
- Added `local-ot3-firmware-builder` image.
- Copies local_ot3_firmware_builder.sh script into image as build.sh
- Tested by building image, running container with it, and building ot3-firmware simulators
- Test script 
```shell
docker buildx build --load --target ot3-firmware-local-builder --tag ot3-firmware-local-builder:test . && docker run --rm -it -v "${PWD}"/../../ot3-firmware:/ot3-firmware -v "${PWD}"/../../opentrons:/opentrons ot3-firmware-local-builder:test bash
```
**Issue:** When building initially inside the container, if your bind mounted `ot3-firmware` repo already has a `build-host` or `stm32-tools` folder you will get an error about cache paths not being correct. The solution for this is to delete both of these folders and rebuild.
**Question:** I am wondering if there is …
> feat: Create local-ot3-firmware-builder image and build script

- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/service_builder_orchestrator.py
- emulation_system/emulation_system/compose_file_creator/input/configuration_file.py
- emulation_system/tests/compose_file_creator/conversion_logic/conftest.py
- emulation_system/tests/compose_file_creator/conversion_logic/test_builder_creation_logic.py
- emulation_system/tests/compose_file_creator/conversion_logic/test_source_code_insertion.py
Add logic to determine whether or not a builder container needs to be added to the docker-compose file. 
Currently the methods to actually add the builder containers are stubbed with print statements. Will be adding the actual containers in another PR
- Create 3 new on SystemConfigurationModel: `local_ot3_builder_required`, `local_opentrons_modules_builder_required`, and `local_monorepo_builder_required`
- If the above methods return `True` create the respective builders inside of `service_builder_orchestrator.py`
- Moved source code fixtures in `test_source_code_insertion.py` to conftest so they can be used inside of `test_builder_creation_logic.py`
- Changed above fixtures to return `Dict[str, Any]` instead of `RuntimeComposeFileModel` so they can be used to create a …
> feat: Add builder container addition logic (RQA-372)

- docker/Dockerfile
- emulation_system/emulation_system/compose_file_creator/config_file_settings.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/__init__.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/concrete_local_ot3_firmware_builder_builder.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/concrete_ot3_state_manager_builder.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/service_builder_orchestrator.py
- emulation_system/tests/compose_file_creator/conversion_logic/conftest.py
- emulation_system/tests/compose_file_creator/conversion_logic/service_builders/test_concrete_local_ot3_firmware_builder_builder.py
- emulation_system/tests/compose_file_creator/conversion_logic/service_builders/test_concrete_ot3_service_builder.py
- emulation_system/tests/compose_file_creator/conversion_logic/test_healthcheck.py
Add ConcreteLocalOT3FirmwareBuilderBuilder to create `local-ot3-firmware-builder` container.
- Add default values for all `OPENTRONS_SOURCE_DOWNLOAD_LOCATION` and `OT3_FIRMWARE_SOURCE_DOWNLOAD_LOCATION` builds args for `ot3-firmware-source` target in Dockerfile. Have to do this because `ot3-firmware` builder requires both the monorepo and ot3-firmware repo. But you can have a configuration where one is local and one is remote. How this configuration will work is during build time either `latest` or a commit sha will be downloaded for both monorepo and ot3-firmware repo. If there are any bind mounts added at runtime, they will override the repos downloaded during build time. 
- Make local-ot3-firmware-builder inherit from `ot3-firmware-source
- Add logic for building volume names, volume …
> feat: Create ConcreteLocalOT3FirmwareBuilderBuilder (RQA-371)

- configuration.json
- docker/Dockerfile
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/concrete_can_server_service_builder.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/concrete_emulator_proxy_service_builder.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/concrete_input_service_builder.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/concrete_ot3_service_builder.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/concrete_ot3_state_manager_builder.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/concrete_smoothie_service_builder.py
- emulation_system/emulation_system/compose_file_creator/errors.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/hardware_model.py
- emulation_system/emulation_system/compose_file_creator/utilities/shared_functions.py
- emulation_system/emulation_system/opentrons_emulation_configuration.py
- emulation_system/tests/command_creators/test_emulation_system.py
- emulation_system/tests/compose_file_creator/conversion_logic/conftest.py
- emulation_system/tests/compose_file_creator/conversion_logic/service_builders/test_concrete_can_server_service_builder.py
- emulation_system/tests/compose_file_creator/conversion_logic/service_builders/test_concrete_emulator_proxy_service_builder.py
- emulation_system/tests/compose_file_creator/conversion_logic/service_builders/test_concrete_ot3_service_builder.py
- emulation_system/tests/compose_file_creator/conversion_logic/service_builders/test_concrete_smoothie_service_builder.py
- emulation_system/tests/compose_file_creator/conversion_logic/test_pure_functions.py
- emulation_system/tests/compose_file_creator/conversion_logic/test_source_code_insertion.py
- emulation_system/tests/compose_file_creator/input/hardware_models/test_hardware_model.py
- emulation_system/tests/compose_file_creator/utilities/test_substitute_yaml_values.py
- emulation_system/tests/test_configuration.json
Add .git folder to deal with new versioning.
Add OPENTRONS_PROJECT when building the monorepo for the OT-3
- Use upstream dockerfile front end syntax to gain usage of `--keep-git-dir` option for `ADD` command
- Utilize `--keep-git-dir=true` for all pulls from Github
- Add `OPENTRONS_PROJECT=ot3` to all instances of building the monorepo for OT-3
- Update tests
Medium, but soon to be a non-issue
Kinda not a fan of using the upstream Dockerfile syntax because breaking changes might be pushed to it. But this is the only way to maintain the cache. BUT this will not be an issue when https://github.com/Opentrons/opentrons-emulation/pull/230 is finished because adding the source code will be the last step in the Dockerfile and all building of source will be done at runtime of the containers.
> chore: Add .git folder and OPENTRONS_PROJECT env var

- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/concrete_emulator_proxy_service_builder.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/modules/module_model.py
This is for compatibility with https://github.com/Opentrons/opentrons/pull/12778
- Override default value of `use_local_host` to `False`
- Make emulator proxy build from `source-location`
I am considering merging this even with failing all the failing CI.
All these CI checks are going to change with release-v4.0.0 and this is just a stop gap until then.
Seems a waste of time to fix these if they are going to removed/changed
What I did instead was test manually.
To start I tested this against the `latest` version of the monorepo. As expected it failed, because the env var was not being used, therefore it the host was referenced as `127.0.0.1` and not the container id.
The next test was to reference the branch from https://github.com/Opentrons/opentrons/pull/12778 in my configuration file …
> chore: Add use_local_host: False to default em proxy settings

- docker/entrypoints/opentrons_modules_builder.sh
- docker/entrypoints/ot3_firmware_builder.sh
- emulation_system/emulation_system/compose_file_creator/config_file_settings.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/input_services.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/ot3_firmware_builder_service.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/ot3_services.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/service_info.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/service_orchestrator.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/robots/ot2_model.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/robots/ot3_model.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/robots/robot_model.py
- emulation_system/emulation_system/compose_file_creator/output/runtime_compose_file_model.py
- emulation_system/emulation_system/compose_file_creator/pipette_utils/__init__.py
- emulation_system/emulation_system/source.py
- emulation_system/tests/compose_file_creator/conversion_logic/service_builders/test_concrete_local_ot3_firmware_builder_builder.py
- emulation_system/tests/compose_file_creator/conversion_logic/service_builders/test_concrete_ot3_service_builder.py
- emulation_system/tests/compose_file_creator/conversion_logic/service_builders/test_concrete_smoothie_service_builder.py
- emulation_system/tests/compose_file_creator/conversion_logic/test_custom_env_vars.py
- emulation_system/tests/compose_file_creator/conversion_logic/test_extra_service_creation.py
- emulation_system/tests/compose_file_creator/conversion_logic/test_healthcheck.py
- emulation_system/tests/compose_file_creator/conversion_logic/test_source_code_insertion.py
- emulation_system/tests/compose_file_creator/input/hardware_models/robots/test_ot2.py
- emulation_system/tests/e2e/conftest.py
- emulation_system/tests/e2e/consts.py
- emulation_system/tests/e2e/dataclass_helpers.py
- emulation_system/tests/e2e/docker_interface/ot3_containers.py
- emulation_system/tests/e2e/helper_functions.py
- emulation_system/tests/e2e/results/ot3_results.py
> NOTE: Probably easiest to view each commit individually!!
Rework pipettes to allow for specification of pipettes on emulated Flex
- Integrate `pipette_utils` package into the repo's `compose-file-creator` framework
- Separate singular Flex pipette container into `left` and `right` pipette containers
- Add Flex "Pipette Configuration" environment variable to ot3-firmware-builder in prep for eeprom file generation script
- Add eeprom volumes to facillitate ot3-firmware-builder pushing eeprom.bin files into pipette and gripper containers
Change notes are captured inside of each commit to this PR.
View them [here](https://github.com/Opentrons/opentrons-emulation/pull/261/commits)
**High Risk** for the following reasons:
- [Volume naming …
> feat: Update pipette specification for Flex and OT-2

- .github/workflows/e2e-tests.yaml
- .github/workflows/emulation-system-lint-test.yaml
- docker/Dockerfile
Emulation was failing during the docker build stage (not the source code build stage). 
I had an old version of docker-compose on my laptop and the `ADD` command worked different on my laptop compared to CI or my server. 
- Not getting zipfile anymore. 
- Based on docker documentation, https://docs.docker.com/engine/reference/builder/#adding-a-git-repository-add-git-ref-dir , I should be adding the .git version of the repo. 
- Now it just downloads that whole repo as a folder. Way nicer
- So no need for unzip and mv command
None
Low, I mean I could break it MORE. But it's currently unusable so the only one that would suffer would be me.
> fix: Fix emulation failing to build

- emulation_system/emulation_system/compose_file_creator/pipette_utils/__init__.py
- emulation_system/emulation_system/compose_file_creator/pipette_utils/data_models.py
- samples/ot3/ot3_local.yaml
Add special case when a mount does not have pipette
- Added EMPTY classmethod om PipetteInfo to generate what an empty pipette is mounted.
- When pipette is not specifed automatically use EMPTY pipette type
None
Low
> feat: Add support for empty pipette mounts

- emulation_system/tests/e2e/results/ot3_results.py
- emulation_system/tests/e2e/system_mappings.py
- emulation_system/tests/e2e/test_definition/system_test_definition.py
- samples/ci/ot3/ot3_remote.yaml
- samples/ci/team_specific_setups/ot3_firmware_development.yaml
Add validation that size of eeprom.bin file is greater than 0 if a pipette is mounted
- Add `left_pipette_expected` and `right_pipette_expected` fields to SystemTestDefinition
- Modify the 3 sample files under test to have different pipette configurations
- Add logic to get size of eeprom.bin files
None
Low
> test: Add validation that pipette eeproms are created correctly

- docker/entrypoints/ot3_firmware_builder.sh
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/monorepo_builder_service.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/ot3_firmware_builder_service.py
- emulation_system/tests/compose_file_creator/conversion_logic/service_builders/test_concrete_local_ot3_firmware_builder_builder.py
The `shared-data` project in the monorepo became a dependency of the `hardware` project in the monorepo. 
This PR accounts for that 
- Add `OPENTRONS_PROJECT: ot3` env var to ot3-firmware-builder and monorepo-builder if robot is flex
- Add shared-data project whenever hardware project is installed
None
Low
> chore: Add shared-data as a dependency for hardware project

- emulation_system/emulation_system/compose_file_creator/config_file_settings.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/abstract_service.py
- emulation_system/emulation_system/compose_file_creator/conversion/service_builders/service_orchestrator.py
- emulation_system/emulation_system/compose_file_creator/input/configuration_file.py
- emulation_system/emulation_system/compose_file_creator/input/hardware_models/hardware_model.py
- emulation_system/tests/compose_file_creator/conversion_logic/test_extra_mounts.py
- emulation_system/tests/compose_file_creator/input/hardware_models/test_hardware_model.py
- samples/ot3/ot3_local_with_custom_mounts.yaml
Allow users to specify arbitrary files and folders to bind in/out of emulation
Remaining Tasks: 
- Remove old and non-functional extra-mounts logic and tests
- Add `ExtraMount` setting to config_file_settings.py
- Add logic to AbstractService.build_service to add any extra mounts to specified containers at runtime
- Add `extra-mounts` field to configuration file
- Add tests for extra mounts
How does the syntax in the configuration file feel?
> feat: Add ability to add custom files and folders to emulation
